// A list of all actions in the system.
import { createTypes } from 'reduxsauce';

export default createTypes(`

  SUPPLIERS_REQUEST
  SUPPLIERS_RECEIVE

  SUPPLIER_REQUEST
  SUPPLIER_RECEIVE

  SUPPLIERS_LAST5_REQUEST
  SUPPLIERS_LAST5_RECEIVE

  SUPPLIERS_ADD_REQUEST
  SUPPLIERS_ADD_RECEIVE

  SUPPLIERS_UPDATE_REQUEST
  SUPPLIERS_UPDATE_RECEIVE

  SUPPLIERS_DELETE_REQUEST
  SUPPLIERS_DELETE_RECEIVE

  PRODUCTS_REQUEST
  PRODUCTS_RECEIVE

  PRODUCT_REQUEST
  PRODUCT_RECEIVE

  PRODUCTS_LAST5_REQUEST
  PRODUCTS_LAST5_RECEIVE

  PRODUCTS_ADD_REQUEST
  PRODUCTS_ADD_RECEIVE

  PRODUCTS_UPDATE_REQUEST
  PRODUCTS_UPDATE_RECEIVE

  PRODUCTS_DELETE_REQUEST
  PRODUCTS_DELETE_RECEIVE

`);
